# DB Config
spring:
  config:
    import: "optional:file:env-dev.properties"
  datasource:
    hikari:
      connection-timeout: 10000
      max-lifetime: 30000
      maximum-pool-size: 30
      minimum-idle: 2
      validation-timeout: 60000 # 아래 테스트 쿼리 주기 설정
      connection-test-query: select '1'
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url:
    username:
    password:

# App Config
info:
  app:
    description: 'development 환경 입니다.'