# DB Config
spring:
  config:
    import: "optional:file:env-prod.properties"
  datasource:
    hikari:
      connection-timeout: 10000
      max-lifetime: 30000
      maximum-pool-size: 30
      minimum-idle: 2
      validation-timeout: 60000 # 아래 테스트 쿼리 주기 설정
      connection-test-query: select '1'
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url:
    username:
    password:

security:
  jwt:
    secret-key: ${JWT_SECRET}
    expiration-time: 3600000

# App Config
info:
  app:
    description: 'production 환경 입니다.'