server:
  port: 8080

spring:
  profiles:
    active: local   # local / dev / prod

  # Hibernate 자동 DDL 생성 비활성화
  jpa:
    hibernate:
      ddl-auto: none

logging:
  config: ./config/log4j2/log4j2-${spring.profiles.active}.yml
  level:
    jdbc:
      audit: OFF
      connection: OFF
      sqlonly: OFF
      sqltiming: INFO
      resultset: OFF
      resultsettable: INFO

#p6spy query logging
decorator:
  datasource:
    p6spy:
      enable-logging: true