server:
  port: 8080

spring:
  profiles:
    active: local   # local / dev / prod

  # Hibernate auto DDL generation off
  jpa:
    hibernate:
      ddl-auto: none

  # exclude null value when json serialized
  jackson:
    default-property-inclusion: non_null

logging:
  config: ./config/log4j2/log4j2-${spring.profiles.active}.yml
  level:
    jdbc:
      audit: OFF
      connection: OFF
      sqlonly: OFF
      sqltiming: INFO
      resultset: OFF
      resultsettable: INFO

#p6spy query logging
decorator:
  datasource:
    p6spy:
      enable-logging: true